apiVersion: v1
kind: Service
metadata:
  name: lfkwebapp-service
  labels:
    app: lfkwebapp-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 443
    protocol: TCP
    targetPort: 443
    nodePort: 32185
  selector:
    app: lfkwebapp
  sessionAffinity: None