apiVersion: v1
kind: Service
metadata:
  name: sampleapp-service
  labels:
    app: sampleapp-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: sampleapp
  sessionAffinity: None